export interface Book {
    id: number;
    title: string;
    year: string;
    genre: string;
    desc: string;
    synopsis: string;
    buyLink: string;
    readLink: string;
    coverImage: string;
}

export const books: Book[] = [
    {
        id: 1,
        title: "The Silent Echo",
        year: "2024",
        genre: "Thriller",
        desc: "In a room that doesn't exist, a voice answers back.",
        synopsis: "Elara finds a door in her apartment that wasn't there yesterday. Behind it lies a perfect replica of her childhood bedroom, but with one subtle difference: someone else is already sleeping in the bed. As she investigates, she discovers that the echo in the room answers questions she hasn't asked yet.",
        buyLink: "https://example.com/buy/silent-echo",
        readLink: "/books/1/read",
        coverImage: "https://images.unsplash.com/photo-1605806616949-1e87b487bc2a?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 2,
        title: "Paper Mornings",
        year: "2023",
        genre: "Slice of Life",
        desc: "The quiet art of brewing coffee while the world sleeps.",
        synopsis: "A collection of interconnected short stories revolving around a small, 24-hour cafe in Tokyo. From the overworked salaryman to the insomniac artist, everyone leaves a piece of themselves behind with their coffee order.",
        buyLink: "https://example.com/buy/paper-mornings",
        readLink: "/books/2/read",
        coverImage: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 3,
        title: "Fractured Glass",
        year: "2023",
        genre: "Thriller",
        desc: "Memories that cut when you try to hold them.",
        synopsis: "After a car accident, Mark loses his ability to recognize faces. But he starts seeing a recurring figure in every reflection—a man who claims to know why Mark survived the crash, and why he shouldn't have.",
        buyLink: "https://example.com/buy/fractured-glass",
        readLink: "/books/3/read",
        coverImage: "https://images.unsplash.com/photo-1542259682-1d547d636015?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 4,
        title: "August Rain",
        year: "2022",
        genre: "Slice of Life",
        desc: "A summer that lasted a decade.",
        synopsis: "Two childhood friends reunite in their hometown to clean out an old attic. As they sort through dusty boxes, they uncover letters that rewrite the history of their friendship.",
        buyLink: "https://example.com/buy/august-rain",
        readLink: "/books/4/read",
        coverImage: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 5,
        title: "The Clockwork Heart",
        year: "2022",
        genre: "Fantasy",
        desc: "Love in the time of gears and steam.",
        synopsis: "In a city powered by clockwork, an automaton falls in love with its creator. A tragedy about consciousness, free will, and the price of distinctiveness.",
        buyLink: "https://example.com/buy/clockwork-heart",
        readLink: "/books/5/read",
        coverImage: "https://images.unsplash.com/photo-1506459225024-1428097a7e18?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 6,
        title: "Midnight Station",
        year: "2021",
        genre: "Mystery",
        desc: "The train arrives, but nobody ever leaves.",
        synopsis: "Passengers board the 12:00 AM train at Central Station, expecting to go home. Instead, they arrive at a station that doesn't appear on any map, where the conductor demands a ticket paid in secrets.",
        buyLink: "https://example.com/buy/midnight-station",
        readLink: "/books/6/read",
        coverImage: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 7,
        title: "Letters to Nobody",
        year: "2021",
        genre: "Drama",
        desc: "Unsent envelopes piling up in the attic.",
        synopsis: "An epistolary novel composed entirely of letters written but never sent. It explores the things we are too afraid to say to the people we love the most.",
        buyLink: "https://example.com/buy/letters-to-nobody",
        readLink: "/books/7/read",
        coverImage: "https://images.unsplash.com/photo-1579402518429-232d18408f6d?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 8,
        title: "Shadows of Red",
        year: "2020",
        genre: "Thriller",
        desc: "Some colors are darker than black.",
        synopsis: "A colorblind painter suddenly starts seeing the color red. It appears only on people who differ from the crowd—people who are about to die.",
        buyLink: "https://example.com/buy/shadows-of-red",
        readLink: "/books/8/read",
        coverImage: "https://images.unsplash.com/photo-1503525148065-d749a02d456a?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 9,
        title: "The Coffee Shop",
        year: "2020",
        genre: "Slice of Life",
        desc: "Conversations overheard at table four.",
        synopsis: "A deep dive into the mundanity of life, observing the fleeting interactions of strangers in a busy metropolitan coffee shop.",
        buyLink: "https://example.com/buy/the-coffee-shop",
        readLink: "/books/9/read",
        coverImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 10,
        title: "Winter's Breath",
        year: "2019",
        genre: "Poetry",
        desc: "Frost patterns on a warm windowpane.",
        synopsis: "A collection of poems exploring isolation, warmth, and the quiet beauty of winter landscapes.",
        buyLink: "https://example.com/buy/winters-breath",
        readLink: "/books/10/read",
        coverImage: "https://images.unsplash.com/photo-1483664852095-d6cc6870705d?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: 11,
        title: "The Last Chapter",
        year: "2019",
        genre: "Meta-Fiction",
        desc: "When the protagonist realizes they are being written.",
        synopsis: "A character in a novel becomes self-aware and attempts to communicate with the author to change their tragic ending.",
        buyLink: "https://example.com/buy/last-chapter",
        readLink: "/books/11/read",
        coverImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=800&auto=format&fit=crop",
    },
];
